## Problem 2 - Data manipulation and selection (4 points)

In this problem you will clean the data from our data file by removing no-data values, convert temperature values in Fahrenheit to Celsius, and split the data into separate datasets using the weather station identification code. We will start this problem by cleaning and converting our temperature data. Please perform the tasks below by writing your code into the codeblocks in each section.

### Tips for completing this problem

- Use **exactly** the same variable names as in the instructions because the tests rely on following the same formatting or variable naming as in the instructions.
- **Please do not**:

    - **Change the file names**. Do all of your editing in the provided `Exercise-5-problem-2.ipynb` file (this file).
    - **Change the existing cell types**. You can add cells, but changing the cell types for existing cells (from code to markdown, for example) will also cause the automated grader to fail. 

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Creating a new dataframe called `selected` that contains select columns from the data file
- Cleaning the new dataframe by removing no-data values
- Creating a new column for temperatures converted from Fahrenheit to Celsius
- Dividing the data into separate dataframes for the Mactan (Cebu) and Hinatuan (Surigao del Sur) stations
- Saving the new dataframes to CSV files
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem
- Uploading your notebook and data files to your GitHub repository for this week's exercise

### Part 1 (0 points)

The first step for this problem is to read the data file `ph_tempdata.csv` again into a variable `data` using pandas. Remember to specify the no-data values (you can copy your code from Problem 1).

In [1]:
#import pandas and read csv file ph_tempdata. na values are specified.
import pandas as pd
data = pd.read_csv("ph_tempdata.csv", sep = ",", na_values = ["*", "**", "***", "****", "*****", "******"])

Check that the first rows of the DataFrame look ok:

In [2]:
# Check first 5 rows
data.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,TEMP,MAX,MIN
0,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-01,79.70,86.00,NaN
1,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-02,79.88,85.64,NaN
2,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-03,82.40,88.52,76.64
3,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-04,82.04,89.24,NaN
4,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-05,81.32,88.52,77.00

Check the number of rows in the DataFrame:

In [3]:
# Check number rows
len(data)

2921

### Part 2 (1 point)

Next, your task is to subset the data and remove rows with missing temperature values.

- Select the columns `STATION`, `DATE`, `TEMP`, `MAX`, and `MIN` from the `data` dataframe and assign them to the variable `selected`
- Remove all rows from `selected` that have NoData in the column `TEMP` using the `dropna()` function

In [4]:
#Select the following panda series and save to new dataframe
selected = data[["STATION", "DATE", "TEMP", "MAX", "MIN"]]

#Drop rows with NaN in TEMP column
selected.dropna(subset = ["TEMP"])

          STATION        DATE   TEMP    MAX    MIN
0     RPM00098646  2017-01-01  79.70  86.00    NaN
1     RPM00098646  2017-01-02  79.88  85.64    NaN
2     RPM00098646  2017-01-03  82.40  88.52  76.64
3     RPM00098646  2017-01-04  82.04  89.24    NaN
4     RPM00098646  2017-01-05  81.32  88.52  77.00
...           ...         ...    ...    ...    ...
2916  RP000098755  2020-12-27  82.58  90.32  74.48
2917  RP000098755  2020-12-28  80.78  85.64    NaN
2918  RP000098755  2020-12-29  81.68  89.24  76.28
2919  RP000098755  2020-12-30  80.42  86.72  76.82
2920  RP000098755  2020-12-31  80.24  86.36    NaN

[2921 rows x 5 columns]

Check that you selected the correct column names:

In [5]:
selected.head()

       STATION        DATE   TEMP    MAX    MIN
0  RPM00098646  2017-01-01  79.70  86.00    NaN
1  RPM00098646  2017-01-02  79.88  85.64    NaN
2  RPM00098646  2017-01-03  82.40  88.52  76.64
3  RPM00098646  2017-01-04  82.04  89.24    NaN
4  RPM00098646  2017-01-05  81.32  88.52  77.00

Check how many rows you have after removing the no-data values:

In [6]:
len(selected)

2921

### Part 3 (1 point)

Next, you can convert the temperature values in Fahrenheit to Celsius.

- Create a new column in `selected` called `Celsius`
- Convert the Fahrenheit temperatures from `TEMP` using the conversion formula below and store the results in the new `Celsius` column.

$$
\Large
\begin{equation}
  T_{\mathrm{Celsius}} = (T_{\mathrm{Fahrenheit}} - 32)~/~1.8
\end{equation}
$$

- Round the values in the `Celsius` column to have 0 decimals (**do not** create a new column, update the current one)
- Convert the `Celsius` values into integers (**do not** create a new column, update the current one)

In [7]:
#Convert TEMP data to Celsius and save to new Panda series
selected["Celsius"] = (selected["TEMP"]-32)/1.8

#Round off and convert Celsius data to integer
selected["Celsius"] = selected["Celsius"].round(0).astype(int)

/tmp/ipykernel_552/3412519401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected["Celsius"] = (selected["TEMP"]-32)/1.8
/tmp/ipykernel_552/3412519401.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected["Celsius"] = selected["Celsius"].round(0).astype(int)

In [8]:
# Check your dataframe
selected.head()

       STATION        DATE   TEMP    MAX    MIN  Celsius
0  RPM00098646  2017-01-01  79.70  86.00    NaN       26
1  RPM00098646  2017-01-02  79.88  85.64    NaN       27
2  RPM00098646  2017-01-03  82.40  88.52  76.64       28
3  RPM00098646  2017-01-04  82.04  89.24    NaN       28
4  RPM00098646  2017-01-05  81.32  88.52  77.00       27

In [9]:
# Check data types
print(selected.dtypes)

STATION     object
DATE        object
TEMP       float64
MAX        float64
MIN        float64
Celsius      int64
dtype: object

### Part 4 (1 point)

Your next task is to divide `selected` into two separate dataframes. Please use the given variable names and write your answer to the codeblock below.

- Select all rows from the `selected` DataFrame with the `STATION` code `RPM00098646` into a variable called `mactan`
- Select all rows from the `selected` DataFrame with the `STATION` code `RP000098755` into a variable called `hinatuan`

In [10]:
#Select rows that have a STATION data of "RPM00098646" and save to new mactan dataframe
mactan = selected.loc[selected["STATION"] == "RPM00098646"]

#Select rows that have a STATION data of "RP000098755" and save to new hinatuan dataframe
hinatuan = selected.loc[selected["STATION"] == "RP000098755"]

In [11]:
# Check the dataframe
print(f"Mactan: \n{mactan.head()}\n")

Mactan:
       STATION        DATE   TEMP    MAX    MIN  Celsius
0  RPM00098646  2017-01-01  79.70  86.00    NaN       26
1  RPM00098646  2017-01-02  79.88  85.64    NaN       27
2  RPM00098646  2017-01-03  82.40  88.52  76.64       28
3  RPM00098646  2017-01-04  82.04  89.24    NaN       28
4  RPM00098646  2017-01-05  81.32  88.52  77.00       27

In [12]:
# Check the dataframe
print(f"Hinatuan: \n{hinatuan.head()}\n")

Hinatuan:
          STATION        DATE   TEMP    MAX    MIN  Celsius
1461  RP000098755  2017-01-01  80.06  84.20  75.20       27
1462  RP000098755  2017-01-02  80.78  85.64  75.92       27
1463  RP000098755  2017-01-03  79.88  85.28    NaN       27
1464  RP000098755  2017-01-04  80.60  86.36  75.38       27
1465  RP000098755  2017-01-05  77.72  89.06    NaN       25

### Part 5 (1 point)

Now you can save your selections to csv files.

- Save the `mactan` DataFrame into the file `Mactan_temps_2019-01_2020-12.csv` (CSV format) 
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Save the `hinatuan` DataFrame into the file `Hinatuan_temps_2019-01_2020-12.csv` (CSV format) 
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Remember to commit both data files to your Exercise 5 repository

In [13]:
# Convert mactan dataframe to csv file separated by commas. old index is omitted, and floating point numbers are limited to two decimal places.
mactan.to_csv("Mactan_temps_2019-01_2020-12.csv", sep = ",", index = False, float_format = "%.2f")

# Convert hinatuan dataframe csv file seaprated by commas. old index is omitted and floating point numbers are limited to two decimal places.
hinatuan.to_csv("Hinatuan_temps_2019-01_2020-12.csv", sep = ",", index = False, float_format = "%.2f")

In [14]:
#Read-only cell for hidden tests :)

### Problem 2 summary

- Was anything unclear to you in Problem 2?
- Did you encounter any problems with decimal formatting?

Also, make sure you:

- Check that your code includes informative comments explaining what your code does
- Commit and push your changes to your GitHub repository for Exercise 5 (including your 2 new data files)

Please write your answers and comments below (**activate the cell by double clicking**).

Everything is clear. Yes, there was a warning/comment but the code still works haha

### On to Problem 3

Now you can continue to [Problem 3: Data analysis](Exercise-5-problem-3.ipynb)